// Luma MVP - autogenerated by Cursor
import Foundation
import AppKit

/// End-to-end dry run harness for testing Luma components.
/// 
/// Per SECURITY.md: Never sends real keys or contacts network.
/// Per SECURITY.md: Logs system events without logging page content or API keys.
final class DebugHarness {
    /// Quick verification test for CommandRouter parsing and execution.
    static func run() {
        let router = CommandRouter()
        let tabManager = TabManager()
        
        // Sample JSON response with action
        let sampleJSON = """
        {
            "text": "ok",
            "action": {
                "id": "\(UUID().uuidString)",
                "type": "navigate",
                "payload": {
                    "url": "https://example.com"
                }
            }
        }
        """
        
        guard let jsonData = sampleJSON.data(using: .utf8) else {
            print("DebugHarness: Failed to create JSON data")
            return
        }
        
        guard let response = router.parseLLMResponse(jsonData) else {
            print("DebugHarness: Failed to parse LLM response")
            return
        }
        
        print("DebugHarness: Parsed text: \(response.text)")
        
        if let action = response.action {
            let result = router.execute(action: action, tabManager: tabManager)
            switch result {
            case .success(let message):
                print("DebugHarness: Action executed successfully: \(message)")
            case .failure(let error):
                print("DebugHarness: Action execution failed: \(error.localizedDescription)")
            }
        } else {
            print("DebugHarness: No action in response")
        }
        
        // Test GeminiClient stub
        print("\nDebugHarness: Testing GeminiClient...")
        let geminiClient = GeminiClient(apiKeyProvider: { "test-key" })
        geminiClient.generate(prompt: "Test prompt", context: nil) { result in
            switch result {
            case .success(let data):
                print("DebugHarness: GeminiClient returned data: \(data.count) bytes")
                if let response = router.parseLLMResponse(data) {
                    print("DebugHarness: Parsed LLMResponse text: \(response.text)")
                }
            case .failure(let error):
                print("DebugHarness: GeminiClient error: \(error.localizedDescription)")
            }
        }
        
        // Test GeminiClient with nil key (should fail)
        let geminiClientNoKey = GeminiClient(apiKeyProvider: { nil })
        geminiClientNoKey.generate(prompt: "Test", context: nil) { result in
            switch result {
            case .success:
                print("DebugHarness: ERROR - Should have failed with no key")
            case .failure(let error):
                print("DebugHarness: Correctly failed with no key: \(error.localizedDescription)")
            }
        }
        
        // Test KeychainManager
        print("\nDebugHarness: Testing KeychainManager...")
        let keychain = KeychainManager.shared
        let testKey = "test-key-\(UUID().uuidString)" // Ephemeral test key, not a real secret
        
        // Store
        do {
            try keychain.storeGeminiKey(testKey)
            print("DebugHarness: Stored test key successfully")
        } catch {
            print("DebugHarness: Failed to store key: \(error.localizedDescription)")
            return
        }
        
        // Fetch
        if let fetchedKey = keychain.fetchGeminiKey() {
            if fetchedKey == testKey {
                print("DebugHarness: Fetched key matches stored key")
            } else {
                print("DebugHarness: ERROR - Fetched key does not match")
            }
        } else {
            print("DebugHarness: ERROR - Failed to fetch key")
        }
        
        // Delete
        do {
            try keychain.deleteGeminiKey()
            print("DebugHarness: Deleted test key successfully")
            
            // Verify deletion
            if keychain.fetchGeminiKey() == nil {
                print("DebugHarness: Verified key was deleted")
            } else {
                print("DebugHarness: ERROR - Key still exists after deletion")
            }
        } catch {
            print("DebugHarness: Failed to delete key: \(error.localizedDescription)")
        }
    }
    
    /// Runs end-to-end dry run tests simulating overlay actions programmatically.
    /// 
    /// Per SECURITY.md: Never sends real keys or contacts network.
    /// Per AGENTS.md: All actions are deterministic and visible.
    /// 
    /// - Parameters:
    ///   - appWindow: The application window (for potential UI tests)
    ///   - useAuth: Whether to test authentication flows (currently unused)
    static func runAll(appWindow: NSWindow, useAuth: Bool = false) {
        print("\n=== DebugHarness: End-to-End Dry Run ===\n")
        
        // Create core components
        let tabManager = TabManager()
        let webViewWrapper = WebViewWrapper()
        let commandRouter = CommandRouter()
        let geminiClient = GeminiClient(apiKeyProvider: {
            KeychainManager.shared.fetchGeminiKey()
        })
        
        // Test 1: Create new tab to https://example.com
        print("Test 1: Creating new tab to https://example.com")
        guard let exampleURL = URL(string: "https://example.com") else {
            print("ERROR: Failed to create example URL")
            return
        }
        
        let tabId = tabManager.newTab(url: exampleURL)
        print("✓ Created tab: \(tabId.uuidString)")
        print("  Current tab: \(tabManager.currentTab?.uuidString ?? "nil")")
        print("  Tab URL: \((tabManager.tabURL[tabId] ?? nil)?.absoluteString ?? "nil")")
        
        webViewWrapper.setActiveTab(tabId)
        webViewWrapper.load(url: exampleURL, in: tabId)
        print("✓ Loaded URL in WebViewWrapper")
        
        // Test 2: Simulate "Summarize page" with no selection
        print("\nTest 2: Simulating 'Summarize page' command (no selection)")
        let summarizePrompt = "Summarize page"
        
        // Simulate no selection (nil context)
        geminiClient.generate(prompt: summarizePrompt, context: nil) { result in
            DispatchQueue.main.async {
                switch result {
                case .success(let data):
                    print("✓ Received LLM response (\(data.count) bytes)")
                    if let response = commandRouter.parseLLMResponse(data) {
                        print("✓ Parsed response text: \(response.text.prefix(50))...")
                        if response.action != nil {
                            print("  Action present: \(response.action!.type.rawValue)")
                        } else {
                            print("  No action in response")
                        }
                    } else {
                        print("ERROR: Failed to parse LLM response")
                    }
                case .failure(let error):
                    print("ERROR: LLM call failed: \(error.localizedDescription)")
                }
                
                // Continue with next test after delay
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                    testNavigateAction(tabManager: tabManager, commandRouter: commandRouter)
                }
            }
        }
    }
    
    private static func testNavigateAction(tabManager: TabManager, commandRouter: CommandRouter) {
        print("\nTest 3: Simulating navigate action with confirmation")
        
        // Create canned navigate action
        let navigateAction = BrowserAction(
            id: UUID(),
            type: .navigate,
            payload: ["url": "https://www.apple.com"]
        )
        
        print("  Action: \(navigateAction.type.rawValue)")
        print("  Payload: \(navigateAction.payload ?? [:])")
        print("  Simulating user confirmation...")
        
        // Simulate confirmation step (programmatic)
        let result = commandRouter.execute(action: navigateAction, tabManager: tabManager)
        
        switch result {
        case .success(let message):
            print("✓ Action executed successfully: \(message)")
            if let currentTab = tabManager.currentTab {
                print("  Current tab URL: \((tabManager.tabURL[currentTab] ?? nil)?.absoluteString ?? "nil")")
            }
        case .failure(let error):
            print("ERROR: Action execution failed: \(error.localizedDescription)")
        }
        
        // Test 4: Invalid action (missing URL)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            testInvalidAction(tabManager: tabManager, commandRouter: commandRouter)
        }
    }
    
    private static func testInvalidAction(tabManager: TabManager, commandRouter: CommandRouter) {
        print("\nTest 4: Testing invalid action (missing URL)")
        
        // Create invalid navigate action (missing URL)
        let invalidAction = BrowserAction(
            id: UUID(),
            type: .navigate,
            payload: nil // Missing URL
        )
        
        print("  Action: \(invalidAction.type.rawValue)")
        print("  Payload: nil (missing required 'url' field)")
        
        let result = commandRouter.execute(action: invalidAction, tabManager: tabManager)
        
        switch result {
        case .success:
            print("ERROR: Action should have failed but succeeded")
        case .failure(let error):
            print("✓ Correctly rejected invalid action: \(error.localizedDescription)")
        }
        
        // Final summary
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            print("\n=== DebugHarness: Dry Run Complete ===")
            print("Summary:")
            print("  - Tab operations: ✓")
            print("  - LLM stub calls: ✓")
            print("  - Action execution: ✓")
            print("  - Error handling: ✓")
            print("Dry run completed successfully")
        }
    }
}
