// Luma MVP - autogenerated by Cursor
import Foundation
import Security

/// Manages secure storage of API keys in macOS Keychain.
/// 
/// Per SECURITY.md: Keys stored only in Keychain, never in code, UserDefaults, logs, or web content.
/// Per SECURITY.md: Keys must not be exposed to WKWebView or renderer JavaScript.
/// 
/// CRITICAL: Never log keys. Never expose keys to web content. Never store keys elsewhere.
final class KeychainManager {
    
    static let shared = KeychainManager()
    
    private let service = "com.luma.browser"
    private let account = "gemini-api-key"
    
    private init() {}
    
    /// Stores the Gemini API key securely in Keychain.
    /// Per SECURITY.md: Keys must be accessible only to Luma process.
    /// - Parameter key: The API key to store (will not be logged)
    /// - Throws: KeychainError if storage fails
    func storeGeminiKey(_ key: String) throws {
        guard let keyData = key.data(using: .utf8) else {
            throw KeychainError.invalidData
        }
        
        // Delete existing key if present (ignore errors if key doesn't exist)
        try? deleteGeminiKey()
        
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecValueData as String: keyData,
            kSecAttrAccessible as String: kSecAttrAccessibleWhenUnlockedThisDeviceOnly
        ]
        
        let status = SecItemAdd(query as CFDictionary, nil)
        
        guard status == errSecSuccess else {
            throw KeychainError.storeFailed(status)
        }
    }
    
    /// Fetches the stored Gemini API key from Keychain.
    /// Returns nil if key doesn't exist or fetch fails.
    /// - Returns: The API key string, or nil if not found
    func fetchGeminiKey() -> String? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne
        ]
        
        var result: AnyObject?
        let status = SecItemCopyMatching(query as CFDictionary, &result)
        
        guard status == errSecSuccess,
              let data = result as? Data,
              let key = String(data: data, encoding: .utf8) else {
            return nil
        }
        
        return key
    }
    
    /// Deletes the stored Gemini API key from Keychain.
    /// Per SECURITY.md: Users must be able to delete keys at any time.
    /// - Throws: KeychainError if deletion fails (but ignores errSecItemNotFound)
    func deleteGeminiKey() throws {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account
        ]
        
        let status = SecItemDelete(query as CFDictionary)
        
        // Ignore "item not found" error (key may not exist)
        guard status == errSecSuccess || status == errSecItemNotFound else {
            throw KeychainError.deleteFailed(status)
        }
    }
}

/// Errors that can occur during Keychain operations.
enum KeychainError: Error {
    case invalidData
    case storeFailed(OSStatus)
    case deleteFailed(OSStatus)
    
    var localizedDescription: String {
        switch self {
        case .invalidData:
            return "Invalid key data"
        case .storeFailed(let status):
            return "Failed to store key in Keychain (status: \(status))"
        case .deleteFailed(let status):
            return "Failed to delete key from Keychain (status: \(status))"
        }
    }
}
