// Luma MVP - autogenerated by Cursor
import Foundation

/// Allowed browser action types per AGENTS.md Browser Action Allowlist.
enum ActionType: String, Codable {
    case new_tab
    case navigate
    case switch_tab
    case close_tab
}

/// Represents a deterministic browser action parsed from LLM response.
/// Per AGENTS.md: Actions must be from a strict allowlist and executed exactly once.
struct BrowserAction: Codable, Identifiable {
    let id: UUID
    let type: ActionType
    let payload: [String: String]?
}

/// LLM response containing text and optional browser action.
struct LLMResponse: Codable {
    let text: String
    let action: BrowserAction?
}

/// A single message in the chat history.
struct ChatMessage: Identifiable, Codable {
    let id: UUID
    let role: Role
    var text: String
    let timestamp: Date
    let pageURL: String?
    let pageTitle: String?

    enum Role: String, Codable {
        case user
        case assistant
    }
    
    init(id: UUID = UUID(), role: Role, text: String, timestamp: Date = Date(), pageURL: String? = nil, pageTitle: String? = nil) {
        self.id = id
        self.role = role
        self.text = text
        self.timestamp = timestamp
        self.pageURL = pageURL
        self.pageTitle = pageTitle
    }
}

/// Conversation summary for token-efficient context
struct ConversationSummary: Codable, Identifiable {
    let id: UUID
    let tabId: UUID
    let summary: String
    let messageRange: ClosedRange<Int> // Which messages this summarizes
    let timestamp: Date
    
    init(id: UUID = UUID(), tabId: UUID, summary: String, messageRange: ClosedRange<Int>, timestamp: Date = Date()) {
        self.id = id
        self.tabId = tabId
        self.summary = summary
        self.messageRange = messageRange
        self.timestamp = timestamp
    }
}

/// Unified history event (browsing or chat)
struct HistoryEvent: Identifiable, Codable {
    let id: UUID
    let timestamp: Date
    let type: EventType
    
    // For browsing events
    let url: String?
    let pageTitle: String?
    
    // For chat events: sessionId = tabId while tab was open; all chats in same tab share one session
    let sessionId: UUID?
    let chatMessages: [ChatMessage]?
    let conversationSummary: String?
    
    enum EventType: String, Codable {
        case pageVisit
        case chatConversation
    }
    
    init(id: UUID = UUID(), timestamp: Date, type: EventType, url: String? = nil, pageTitle: String? = nil, sessionId: UUID? = nil, chatMessages: [ChatMessage]? = nil, conversationSummary: String? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.type = type
        self.url = url
        self.pageTitle = pageTitle
        self.sessionId = sessionId
        self.chatMessages = chatMessages
        self.conversationSummary = conversationSummary
    }
}
