// Luma MVP - autogenerated by Cursor
import Foundation
import SwiftUI
import Combine

/// A single entry in the local navigation history (last N navigations across tabs).
struct HistoryEntry: Identifiable {
    let id = UUID()
    let date: Date
    let title: String
    let url: URL
}

/// Manages browser tab lifecycle and navigation state.
///
/// Per SRS F1 and AGENTS.md: All browser actions must be deterministic and visible.
/// No persistence in MVP (SRS 2.3).
final class TabManager: ObservableObject {
    @Published var tabOrder: [UUID] = []
    @Published var tabURL: [UUID: URL?] = [:]
    @Published var tabTitle: [UUID: String] = [:]
    @Published var currentTab: UUID? = nil

    /// Last N navigations (local only, non-persisted). Cmd+Y shows this list.
    @Published private(set) var navigationHistory: [HistoryEntry] = []
    private let maxHistoryCount = 100

    /// Records a navigation for the history sheet (Cmd+Y).
    func addNavigation(title: String, url: URL) {
        let entry = HistoryEntry(date: Date(), title: title, url: url)
        navigationHistory.insert(entry, at: 0)
        if navigationHistory.count > maxHistoryCount {
            navigationHistory.removeLast()
        }
    }

    func newTab(url: URL?) -> UUID {
        let id = UUID()
        tabOrder.append(id)
        // Start page uses about:blank so back/forward can return to it
        tabURL[id] = url ?? URL(string: "about:blank")!
        currentTab = id
        return id
    }

    func closeTab(_ id: UUID) {
        let wasCurrent = (currentTab == id)
        let closedIdx = tabOrder.firstIndex(of: id)

        tabOrder.removeAll { $0 == id }
        tabURL.removeValue(forKey: id)

        if wasCurrent, let idx = closedIdx {
            if idx > 0 {
                currentTab = tabOrder[idx - 1]
            } else if !tabOrder.isEmpty {
                currentTab = tabOrder[0]
            } else {
                currentTab = nil
            }
        }
    }

    func switchToTab(_ id: UUID) {
        guard tabOrder.contains(id) else { return }
        currentTab = id
    }

    /// Switch to tab by index (0-based). Used for Cmd+1...9.
    func switchToTab(index: Int) {
        guard index >= 0, index < tabOrder.count else { return }
        currentTab = tabOrder[index]
    }

    /// Reorder tabs (drag and drop). Moves tab at sourceIndex to destinationIndex.
    func moveTab(from sourceIndex: Int, to destinationIndex: Int) {
        guard sourceIndex >= 0, sourceIndex < tabOrder.count,
              destinationIndex >= 0, destinationIndex <= tabOrder.count else { return }
        let id = tabOrder.remove(at: sourceIndex)
        let toOffset = destinationIndex > sourceIndex ? destinationIndex - 1 : destinationIndex
        tabOrder.insert(id, at: toOffset)
    }

    func navigate(tab id: UUID, to url: URL) {
        guard tabOrder.contains(id) else { return }
        tabURL[id] = url
    }
    
    func updateTitle(tab id: UUID, title: String) {
        tabTitle[id] = title
    }

    func navigateCurrentTab(to url: URL) {
        guard let currentId = currentTab else { return }
        tabURL[currentId] = url
    }

    func currentURL() -> URL? {
        guard let id = currentTab else { return nil }
        return tabURL[id] ?? nil
    }

    func currentIndex() -> Int? {
        guard let id = currentTab else { return nil }
        return tabOrder.firstIndex(of: id)
    }

    func tabCount() -> Int {
        tabOrder.count
    }
}
